### PR TITLE
Modify GetRows() and GetRowsFormatted() to return nullable IList

### LINKED ISSUE #24: SheetHelper.GetRows() can return null, but the return type is not considered nullable
If there is no data in the sheet in the requested range, `GetRows()` can sometimes return `null`, but the method itself is set to return `IList<IList<object>>`, rather than `IList<IList<object>>?`

### PR DESCRIPTION
**Pull request by HughMacdonald**
Fixes #24

### CODE REVIEW

**Comment by SteveWinward** [comment]
@HughMacdonald thank you for finding this issue and helping fix it. One concern I have is if we change the signature to a nullable return type, does that break people already using this method expecting a non nullable return?  If so, would it be better to check inside the method if the result is null and then return an empty list collection with zero elements to avoid a null return?

**Comment by HughMacdonald** [comment]
The trouble is that it can return null already, and does if there isn't any data, but doesn't tell the user that. So people may have done what I've done and specified that the variable it's being set in is nullable. Otherwise you may end up with a variable that isn't considered nullable that still has a null value

**Comment by SteveWinward** [comment]
Understood. Thank you for sharing your perspective. Will accept the PR and update the version number so a new nuget version is released. I’ll reply to the thread when the new version is released.

**Comment by SteveWinward** [comment]
@HughMacdonald just released version 1.0.55

**Pull request merged**
